services:
  wonderfood.worker:
    image: wonderfood.worker
    build:
      context: .
      dockerfile: src/Wonderfood.Worker/Dockerfile


  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - wonderfood