services:
  app:
    image: felipefabricio/wdf.pagamentos.worker
    container_name: pagamentos-worker
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "9000:8080"
      - "9001:8081"
    env_file:
      - .env
    networks:
      - wonderfood_network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - wonderfood_network

volumes:
  mongodb_data:

networks:
  wonderfood_network:
    external: true
