services:
  wonderfood.worker:
    image: wonderfood.worker
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
        - mongodb
    ports:
      - "5000:80"
      - "5001:443"
    networks:
      - wonderfood
    env_file:
      - .env

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - wonderfood