
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgt-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgt-worker
  template:
    metadata:
      labels:
        app: pgt-worker
    spec:
      containers:
        - name: pgt-worker
          image: felipefabricio/wdf.pagamentos.worker:latest
          ports:
            - containerPort: 8080
              name: pgt-worker
              protocol: TCP
          resources:
            limits:
              cpu: "0.5"
              memory: "1Gi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
          env:
            - name: MONGODB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: mongo-connection-secret
                  key: connectionString
                  
            - name: MONGO_INITDB_DATABASE
              value: Wonderfood
              
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-user-secret
                  key: user
                  
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-password-secret
                  key: password
                  
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-host-secret
                  key: host
                  
      imagePullSecrets:
        - name: dockerhub-secret

---

apiVersion: v1
kind: Service
metadata:
  name: pgt-worker-service
spec:
  type: LoadBalancer
  selector:
    app: pgt-worker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pgt-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pgt-worker
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
