
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgt-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgt-worker
  template:
    metadata:
      labels:
        app: pgt-worker
    spec:
      containers:
        - name: pagamentos-worker
          image: felipefabricio/wdf.pagamentos.worker:latest
          ports:
            - containerPort: 80
              name: pagamentos-worker
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /_ready
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 600
          resources:
            limits:
              cpu: "0.5"
              memory: "1Gi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
          env:
            - name: MONGODB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: mongo-connection-secret
                  key: connectionString
            - name: MONGO_INITDB_DATABASE
              value: Wonderfood
      imagePullSecrets:
        - name: dockerhub-secret


---

apiVersion: v1
kind: Service
metadata:
  name: pagamentos-worker-service
spec:
  type: LoadBalancer
  selector:
    app: pagamentos-worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pagamentos-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pagamentos-worker
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
